### ISSUE TITLE
Local Installation Fail - Package spatstat.core not available

### ISSUE THREAD

**Issue by aditipate** [ncats/public_sequin#4]
Hello, I am interested in running SEQUIN for analysis and visualization of bulk and single-cell RNA-seq data. I have followed the documentation steps for installing SEQUIN locally, however when running the command source("install_sequin.R") to run the installation script and activate the SEQUIN project, I run into an issue with package installation.  As of now the installation fails due to the spatstat.core package not being available/deprecated. Here is the exact error message:

``` 
Error: package 'spatstat.core' is not available
Traceback (most recent calls last):
19: source("install_sequin.R")
18: withVisible(eval(ei, envir))
17: eval(ei, envir)
16: eval(ei, envir)
15: renv::install(cranPackages) at install_sequin.R#17
14: retrieve(packages)
13: handler(package, renv_retrieve_impl(package))
12: renv_retrieve_impl(package)
11: withCallingHandlers(renv_available_packages_latest(package), 
        error = function(err) stopf("package '%s' is not available", 
            package))
10: renv_available_packages_latest(package)
 9: map(errors$data(), warning)
 8: lapply(x, f, ...)
 7: FUN(X[[i]], ...)
 6: withRestarts({
        .Internal(.signalCondition(cond, message, call))
        .Internal(.dfltWarn(message, call))
    }, muffleWarning = function() NULL)
 5: withOneRestart(expr, restarts[[1L]])
 4: doWithOneRestart(return(expr), restart)
 3: <condition-handler>(...)
 2: stopf("package '%s' is not available", package)
 1: stop(sprintf(fmt, ...), call. = call.)  
``` 

According to spatstat.core repository (https://github.com/spatstat/spatstat.core) the package is marked for deletion and will be replaced by two packages, spatstat.explore and spatstat.model. Additionally the package spatstat.core was removed from the CRAN repository and formerly available versions can only be obtained from the CRAN archive. Although it seems spatstat.core isn't being used directly in the Shiny app, the package is a dependency for Seurat which is being used in SEQUIN. Any help to resolve this issue with spatstat.core package would be greatly appreciated. Thanks!

**Comment by djsmith17** [comment]
Hi @aditipate Thank you for sharing your issue. 

After investigating the requirement of the spatstat.core package for running SEQUIN, I have confirmed that It is not required for SEQUIN to run. This dependency has been deprecated and replaced since the last update to the SEQUIN app, however it was listed as a required package to be installed. Since spatstat.core is not available, the list of required packages detailed in the renv.lock file has been updated with the more modern requirements and SEQUIN does still work with the upgraded spatstat packages. A pull request has been opened in public_sequin GitHub repo with the updated renv.lock list of packages so this error can be avoided in the future. I will send another update when this change is available on the master branch and can be pulled into your personal repos.

Please see this attachment for more information about my process.
[SEQUIN Support_spatstat package issue.pdf](https://github.com/ncats/public_sequin/files/12629470/SEQUIN.Support_spatstat.package.issue.pdf)
